name: skillearn demo 

on:
  push:

jobs:
  build_deploy:
    runs-on: self-hosted

    steps:
      - name: clone to runner 
        uses: actions/checkout@v3

      - name: install jdk if needed
        uses: actions/setup-java@v3
        with:
          java-version: 17 
          distribution: temurin

      - name: login into docker-hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{secrets.DOCKERHUB_TOKEN }} 

      - name: docker build images
        run: docker build -t  ${{ secrets.DOCKERHUB_USERNAME }}/java:v1  -f backend/Dockerfile /backend

      - name: push into docker-hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/java:v1
      - name: docker build containers
        run: docker run -d ${{ secrets.DOCKERHUB_USERNAME }}/java:v1


      
